config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  get '/about', to: 'pages#about'

  get '/order', to: 'pages#order'
  get '/dashboard', to: 'pages#dashboard'

  # get '/recipes', to: 'recipes#index'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'


  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup', to: 'chefs#new', as: 'signup'
  resources :chefs, except:[:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except:[:destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true, length: {minimum: 10, maximum: 500}

  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> {order(updated_at: :desc)}
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    # @recipes = Recipe.all
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end

  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
    @comment = Comment.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe successfully updated"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    if @recipe.destroy
      flash[:success] = "Recipe successfully deleted"
      redirect_to recipes_path
    else
      render 'edit'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids: [])
  end

  def require_same_user
    if current_chef != @recipe.chef and !current_chef.admin?
      flash[:danger] = "You can not performace this action"
      redirect_to root_path
    end
  end
end

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Nome of the recipe", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Steps of the recipe", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-offset-2 col-md-8">
              <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input-checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit class: "btn btn-primary btn-md" %>
          </div>
        </div>
      <% end %>
      <div class="col-md-4 col-md-offset-4">
        [<%= link_to "Cancel request and return to recipes listing", recipes_path, class: "cancel-request" %>]
      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <div class="col-sm-2 center">
      <section class="chef-info">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
      <small>Chef: <%= recipe.chef.chefname.split(' ')[0] %></small>
    </div>
    <div class="col-sm-6">
      <div class="well">
        <h5><%= link_to "#{recipe.name}", recipe_path(recipe) %></h5>
        <hr />
        <p><%= truncate(recipe.description, length: 100) %></p>
        <% if recipe.ingredients.any? %>
          <p>Ingredients: <%= render recipe.ingredients %></p>
        <% end %>
        <span class="quiet">
          <small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small> |
          <small>Has <%= pluralize(recipe.comments.count, "comment") %></small>
        </span>
      </div>
    </div>
    <div class="col-sm-4">
      <h1>Recipe's Image</h1>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(recipe),
                                            method: :delete,
                                            data: {confirm: "Are you sure you want to delete?"},
                                            class: "btn btn-xs btn-danger" %>

        </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: @recipe.name.capitalize %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all #{@recipes.count} recipes" %>

<div class="container">
  <div class="center">
    <%= will_paginate %>
  </div>

  <%= render 'recipe', obj: @recipes %>
  <div class="center">
    <%= will_paginate %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="container">
    <div class="row">
      <div class="col-sm-8">
        <div class="well">
          <h4><strong>Steps:</strong></h4>
          <hr />
          <p><%= simple_format(@recipe.description) %></p>
          <hr />
          <% if @recipe.ingredients.any? %>
            <p>Ingredients: <%= render @recipe.ingredients %></p>
          <% end %>
        </div>
        <div class="pull-right pull-up">
          <small><em>Created</em> <%= time_ago_in_words(@recipe.created_at)%> <em>ago by</em></small>
          <small><%= @recipe.chef.chefname %></small>
          <small><%= link_to gravatar_for(@recipe.chef, size: 40), recipes_path, class: "chef-info"%></small>
        </div>
      </div>
      <div class="col-sm-4">
        <h1>Recipe's Image</h1>
      </div>
    </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="recipe-actions">
        <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
          <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this recipe", recipe_path(@recipe),
                                            method: :delete,
                                            data: {confirm: "Are you sure you want to delete?"},
                                            class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "Back to recipes", recipes_path, class: "btn btn-xs btn-primary" %>
      </div>
    </div>
  </div>
  <hr />
</div>

<% if logged_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h3>Comments: </h3>
        <hr>
        <%= form_for([@recipe, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <div class="form-group">
            <div class="control-label col-md-2">
              <%= f.label :Comment %>
            </div>
            <div class="col-md-8">
              <%= f.text_area :description, rows: 6, class: "form-control", placeholder: "Enter comment here", autofocus: true %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              <%= f.submit "Submit comment", class: "btn btn-primary btn-md" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<% if @recipe.comments != 0 %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h3>Prior comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
</div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h3>No comments yet!</h3>
      </div>
    </div>
  </div>
<% end %>