config/routes.rb
Rails.application.routes.draw do


  root 'pages#home'
  get '/about', to: 'pages#about'

  get '/order', to: 'pages#order'
  get '/dashboard', to: 'pages#dashboard'

  # get '/recipes', to: 'recipes#index'
  # get 'recipes/new', to: 'recipes#new', as: 'new_recipe'
  # post '/recipes', to: 'recipes#create'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipe'


  resources :recipes do
    resources :comments, only: [:create]
  end

  get '/signup', to: 'chefs#new', as: 'signup'
  resources :chefs, except:[:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :ingredients, except:[:destroy]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: [:edit, :update, :show]
  before_action :require_logged_in, except: [:show, :index]
  before_action :require_admin, except: [:show, :index]

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient successfully created"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 7)
  end

  def edit

  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingrediente successfully updated"
      redirect_to ingredient_path(@ingredient)
    else
      render 'edit'
    end
  end

  def destroy

  end

  private

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def require_logged_in
    if !logged_in?
      # flash[:danger] = "You must be logged"
      redirect_to root_path
    end
  end

  def require_admin
    if (logged_in? && !current_chef.admin?)
      flash[:danger] = "Only admin can performace that action"
      redirect_to ingredients_path
    end
  end
end

app/views/ingredients/_form.html.erb
<%= render 'shared/errors', obj: @ingredient %>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :name %>
          </div>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Nome of the ingredient", autofocus: true %>
          </div>
        </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient",
                                                    class: "btn btn-primary btn-md") %>
          </div>
        </div>
      <% end %>
      <div class="col-md-4 col-md-offset-4">
        [<%= link_to "Cancel request and return to ingredients listing", ingredients_path, class: "cancel-request" %>]
      </div>
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %>&nbsp;</span>

app/views/ingredients/edit.html.erb
<%= render 'shared/page_title', title: "Enter a New Ingredient" %>

<% if logged_in? && current_chef.adim? %>
  <%= render 'form' %>
<% end %>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<div class="container">
  <div class="center">
    <%= will_paginate %>
  </div>
  <% @ingredients.each do |ing| %>
    <div class="row">
      <div class="col-sm-2">
        <table>
          <tr>
            <% if logged_in?  && current_chef.admin? %>
              <%= link_to "Edit this ingredient", edit_ingredient_path(ing),
                                              class: "btn btn-primary btn-sm btn-container-center btn-container-col-center" %>
            <% end %>
          </tr>
        </table>
      </div>
      <div class="col-sm-8">
        <div class="well">
          <h5>The ingredient <%= link_to "#{ing.name.capitalize}", ingredient_path(ing), class: "chef-title" %> is present in <%= pluralize(ing.recipes.count, "recipe") %></h5>
          <hr />
          <ul>
            <% ing.recipes.each do |recipe| %>
              <li id="listing">
                <%= link_to "#{recipe.name}", recipe_path(recipe), target: "_blank"%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="center">
    <%= will_paginate %>
  </div>
</div>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: "Enter a New Ingredient" %>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: "Ingredient #{@ingredient.name}' recipes" %>


<% if @ingredient.recipes.count != 0 %>
  <div class="container">
    <h4 class="center">Recipe's containing <%= @ingredient.name %></h4>
    <hr />
    <div class="center">
      <%= will_paginate @ingredient_recipes %>
    </div>
    <%= render 'recipes/recipe', obj: @ingredient_recipes %>
    <div class="center">
      <%= will_paginate @ingredient_recipes %>
    </div>
  </div>
<% else %>
  <div class="container center">
    <h4><%= @ingredient.name %> has no recipes yet!</h4>
  </div>
<% end %>